### ISSUE TITLE
Can't use dithering with black&white vector file, result is all black

### ISSUE THREAD

**Issue by irlaec** [mrbeam/MrBeamPlugin#455] opened 2019-04-11 14:30 UTC
Reported by Oli Bischoff:

When trying to laser any black and white vector file with dithering, the result is an all black image.

I reproduced it with [this SVG](https://game-icons.net/1x1/delapouite/school-of-fish.html)

**Comment by hungerpirat** [comment] 2019-11-24 16:13
I tested and reproduced it. switching engraving mode to 'basic' is a workaround. Looks like dithering and separation of images are somehow interfering.

**Comment by hungerpirat** [comment] 2020-01-17 08:26
fixed by fde7aa4

**Closed** 2020-01-17 08:28 UTC
Labels: SVG, bug
