### ISSUE TITLE
Camera Calibration: Show warning if device is not homed.

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#860] opened 2020-06-09 14:41 UTC
Curently the system does not serve a picture wir recognised markes in the camera calibration screen if the device is not homed. This might not be a big deal, since the user needs to do a engraving job right before. But still, we should at least show a warning.

Currently happens in BETA (0.6.11) and also in Stable (0.6.12).

Another option might to to drop this rule that we do not take pictures if not homed....

**Comment by Gallore** [comment] 2020-06-09 14:42
![](https://github.trello.services/images/mini-trello-icon.png) [Camera Calibration: show warning if not homed.](https://trello.com/c/QIoq5gP2/531-camera-calibration-show-warning-if-not-homed)

**Comment by amrsoll** [comment] 2020-07-02 21:44
Closing issue seeing this is a duplicate of #250

**Closed by amrsoll** 2020-07-02 21:44 UTC
Labels: bug
