### ISSUE TITLE
Logfiles: Switch to tmpfs on PROD devices

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#44] opened 2017-04-18 10:05 UTC
On PROD devices all logfiles (octoprint log etc..) should be written to a tmpfs (non-persistent FS) to reduce write operations on SD card.
However this should not get implemented unless we feel confident enough that we don't need the logs from our prod devices. The first devices we deliver should still log persistently...

DEV devices should log persitnently.

**Comment by amrsoll** [comment] 2020-07-02 22:27
Closing, as the issue is broadened in #826

**Closed by amrsoll** 2020-07-02 22:27 UTC
Labels: enhancement
